### ISSUE TITLE
mvn package fails

### ISSUE THREAD

**Issue by kevin-isa-coder** [EXIficient/exificient#35] opened 2023-02-27 23:04 UTC
Running mvn package on the exificient-1.0.4 tag or the latest produces this (partial) output:
 FAILURE! - in com.siemens.ct.exi.main.ParallelTest
testParallelEncodeWithThreadLocalFactory(com.siemens.ct.exi.main.ParallelTest)  Time elapsed: 0.214 sec  <<< ERROR!
com.siemens.ct.exi.core.exceptions.EXIException:
Problem occured while building XML Schema Model (XSModel)!
. [xs-warning] schema_reference.4: Failed to read schema document 'http://www.w3.org/2001/XMLSchema.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
. [xs-error] src-resolve: Cannot resolve the name 'xs:schema' to a(n) 'element declaration' component.
        at com.siemens.ct.exi.main.ParallelTest.getExiFactory(ParallelTest.java:153)
        at com.siemens.ct.exi.main.ParallelTest.testParallelEncode(ParallelTest.java:245)
        at com.siemens.ct.exi.main.ParallelTest.testParallelEncodeWithThreadLocalFactory(ParallelTest.java:234)

mvn -v
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: C:\apache-maven-3.9.0
Java version: 1.8.0_202, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_202\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by danielpeintner** [comment] 2023-03-01 11:18
`mvn package` runs first `test` and `javadoc` also.

In your case a test fails since it cannot reach  'http://www.w3.org/2001/XMLSchema.xsd'. Maybe a restriction of your company network. I just now pushed a commit so that this file is fetched locally. Please try again. 

Another quick workaround is to run `package` it without `test` and `javadoc` 
see `mvn package -DskipTests -Dmaven.javadoc.skip=true`

**Comment by kevin-isa-coder** [comment] 2023-03-01 14:23
Thanks.  I will try it.  Note that if you put 'http://www.w3.org/2001/XMLSchema.xsd' into a browser, it redirects you to https, which may have something to do with it.

**Comment by danielpeintner** [comment] 2023-03-01 15:42
> Thanks. I will try it. Note that if you put 'http://www.w3.org/2001/XMLSchema.xsd' into a browser, it redirects you to https, which may have something to do with it.

Probably this is causing the issue. I am not sure though.
Anyhow, there is not much we can do since the error comes from the Xerces2 library we are simply using...

**Comment by kevin-isa-coder** [comment] 2023-03-01 17:07
confirming that 'mvn package' now succeeds.

**Comment by danielpeintner** [comment] 2023-03-02 07:28
I assume we can close the issue?
Please re-open if you feel the issue is not resolved.

**Closed by danielpeintner** 2023-03-02 07:28 UTC
